### ISSUE TITLE
[Bug] Main window's size isn't saved

### ISSUE THREAD

**Issue by bovirus** [Leo-Corporation/InternetTest#454]
### What is the bug?

I run the application.
By default the home page don't show "Trace route" button (you should scroll down).
I resize the main window to show the Trace route buttion.
Close the app and re-run.
Again Trace routye button not shown in main page

### How to reproduce the bug?

Run the application

### Screenshots

Standard window
![image](https://github.com/Leo-Corporation/InternetTest/assets/1262554/b84ba288-5fef-4b03-9692-2fd42b5841ad)

Window with higher height and with trace route button
![image](https://github.com/Leo-Corporation/InternetTest/assets/1262554/ddc2222e-350d-49e7-b151-30e6c1694656)

After re-run the application
![image](https://github.com/Leo-Corporation/InternetTest/assets/1262554/bb8384d5-8a51-4c73-8575-e1cbfebbedee)

### Operating System

Windows 10

### What is the version of the operating system?

Windows 10 22H2 64bit italian

### What is the version of the software?

7.61.2307

**Comment by Leo-Peyronnet** [comment]
Thanks for reporting this issue, I'll fix this soon.
