### ISSUE TITLE
[Bug] Require framework desktop runtime 6.x (cannot install if  7.x is already installed)

### ISSUE THREAD

**Issue by bovirus** [Leo-Corporation/InternetTest#456]
### What is the bug?

I check that the installer check availability of framework.net  desktop runtime 6.x.

But only 6.x - not version newer then 6.x.

It refuse to install if you have already installed framework.net runtime 7.x.

To fix it I should install framework,.net desktop runtime 6 laso if I have version 7.x already installed.

I believe that if framework.net runtime 7.x or newer is installed the installer should go away.
 

### How to reproduce the bug?

Install in a system with framework.net desktop runtime 7,x (but without 6.x version).

### Operating System

Windows 10

### What is the version of the operating system?

Windows 10 22H2 64bit italian

### What is the version of the software?

7.61.2307

**Comment by Leo-Peyronnet** [comment]
> It refuse to install if you have already installed framework.net runtime 7.x.

The app project is indeed targeting .NET 6 (Windows), so you'll need to have the .NET 6.0 runtime, even if you have a more recent major version of .NET installed.

> I believe that if framework.net runtime 7.x or newer is installed the installer should go away.

This will be fixed with the next release. I will add code to check if the .NET 6.0 Windows Runtime is installed, and if not, the setup will show an error and close.

Thank you for your feedback.

**Comment by bovirus** [comment]
@Leo-Peyronnet 

Framework 7,x should be compatible with Framework 6,x calls.

Is not possible for the Interbnettest installer to check the framework version and if is 6,x or up (ex. 7.xx) install the application?

**Comment by Leo-Peyronnet** [comment]
> Framework 7,x should be compatible with Framework 6,x calls.

Yes, but the way .NET works is by specifying a target framework in the project file:

https://github.com/Leo-Corporation/InternetTest/blob/c78d1c4f6d164e4d57f5939c436992ce76bf3d85/InternetTest/InternetTest/InternetTest.csproj#L5

Even if upgrading the project to .NET 7 wouldn't break anything, it is impossible to execute an app that targets .NET 6 if you only have .NET 7; you'll still need to have the .NET 6 Windows Desktop runtime to be installed.

> Is not possible for the InternetTest installer to check the framework version and if is 6,x or up (ex. 7.xx) install the application?

The setup will have still to check if the project targeted framework (.NET 6) is installed, even if there's a more recent version installed (such as 7.x).
