### ISSUE TITLE
[Bug] 8.0.0.2401 - Translation issues

### ISSUE THREAD

**Issue by bovirus** [Leo-Corporation/InternetTest#531]
### What is the bug?

@leo

Pelase check screenshots

![image](https://github.com/Leo-Corporation/InternetTest/assets/1262554/de47d7ad-5ae8-4a0c-bfae-6108412f8860)

"N/A" is not translated.
Please add "N/A" to language file.
In Italian is "N/D"

![image](https://github.com/Leo-Corporation/InternetTest/assets/1262554/5369af64-0379-4d9e-8d48-120c1791fa09)

For me "Network" ("Rete" in Italian) if is related to WiFi should be "WiFi" ("WiFi" in Italian))

### How to reproduce the bug?

Please check screenshots

### Operating System

Windows 10

### What is the version of the operating system?

Windows 10 22H2 64bit italian

### What is the version of the software?

8.0.0.2401

**Comment by Leo-Peyronnet** [comment]
I will add translations for the "N/A" string. 
For the "Network" string in the home page, I will modify the string, so it says "WiFi" when connected to a WiFi network and "Network" if it is connected to a non-WiFi network.

**Comment by bovirus** [comment]
@Leo-Peyronnet 

Perfect.
I believe that "Network" or "WifI" is the best solution.
