### ISSUE TITLE
[Bug] 8.0.1.2401 - Network/Wifi seems not work

### ISSUE THREAD

**Issue by bovirus** [Leo-Corporation/InternetTest#535]
### What is the bug?

@Leo-Peyronnet 

My computer is connected via ethernet.

Please check screenshot.

![image](https://github.com/Leo-Corporation/InternetTest/assets/1262554/e4cc7f05-dfd0-45f6-8a9a-206a324ce36f)

It report "Network not connected" (Rete non in linea)

Should be "WiFi not connected".

I updated Italian language

### How to reproduce the bug?

Check screenshot

### Operating System

Windows 10

### What is the version of the operating system?

Windows 10 22H2 64bit italian

### What is the version of the software?

8.0.1.2041

**Comment by Leo-Peyronnet** [comment]
Thanks for reporting this issue, it should now be fixed in 8.0.2.2401.
