### ISSUE TITLE
[Enhancement] Portability 

### ISSUE THREAD

**Issue by paradoxicallist** [Leo-Corporation/InternetTest#622]
### Enhancement

Make InternetTest.exe (not InternetTestProSetup.exe) to create History2.json, NewSynethiaConfig.json and Settings.xml in the same directory instead of C:\Users\User\AppData\Roaming\Léo Corporation\InternetTest Pro\

My Window system is set to reset any change in every machine restart. Then all settings are gone. 
InternetTest.exe sits in another partition which doesn't reset on every machine restart.

**Comment by lpeyr** [comment]
Thanks for the suggestion. Will consider this as a new feature for next version.
